export const UserDetailsTranslations = {
    en: {
        "USER_DETAILS_TAB_ACCOUNT_INFO": "Account",
        "USER_DETAILS_TAB_EMAIL_SETTINGS": "Email settings",
        "USER_DETAILS_TAB_SMS_SETTINGS": "Sms settings",
        "USER_DETAILS_TAB_ROLES": "Roles",
        "USER_DETAILS_TAB_ACTIVITIES": "Activities",
        "USER_DETAILS_TAB_SESSIONS": "Sessions",
        "USER_DETAILS_ACCOUNT_LOGIN": "Primary email",
        "USER_DETAILS_ACCOUNT_LANGUAGE": "Language",
        "USER_DETAILS_ACCOUNT_THEME": "Theme",
        "USER_DETAILS_ACCOUNT_TIME_ZONE": "Time zone",
        "USER_DETAILS_EMAIL_SETTINGS_EMAIL": "Email",
        "USER_DETAILS_EMAIL_SETTINGS_LANGUAGE": "Language",
        "USER_DETAILS_EMAIL_SETTINGS_VERIFIED": "Verified",
        "USER_DETAILS_SMS_SETTINGS_PHONE": "Phone number",
        "USER_DETAILS_SMS_SETTINGS_LANGUAGE": "Language",
        "USER_DETAILS_SMS_SETTINGS_VERIFIED": "Verified",
    },
    ru: {
        "USER_DETAILS_TAB_ACCOUNT_INFO": "Профиль",
        "USER_DETAILS_TAB_EMAIL_SETTINGS": "Настройки email",
        "USER_DETAILS_TAB_SMS_SETTINGS": "Настройки sms",
        "USER_DETAILS_TAB_ROLES": "Роли",
        "USER_DETAILS_TAB_ACTIVITIES": "Активности",
        "USER_DETAILS_TAB_SESSIONS": "Сессии",
        "USER_DETAILS_ACCOUNT_LOGIN": "Основной email",
        "USER_DETAILS_ACCOUNT_LANGUAGE": "Язык интерфейса",
        "USER_DETAILS_ACCOUNT_THEME": "Тема",
        "USER_DETAILS_ACCOUNT_TIME_ZONE": "Часовой пояс",
        "USER_DETAILS_EMAIL_SETTINGS_EMAIL": "Email адрес",
        "USER_DETAILS_EMAIL_SETTINGS_LANGUAGE": "Язык",
        "USER_DETAILS_EMAIL_SETTINGS_VERIFIED": "Верифицировано",
        "USER_DETAILS_SMS_SETTINGS_PHONE": "Номер телефона",
        "USER_DETAILS_SMS_SETTINGS_LANGUAGE": "Язык",
        "USER_DETAILS_SMS_SETTINGS_VERIFIED": "Верифицировано",
    }
};
